# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.0

builder:
  image: og-marl
  dockerfile: ./Dockerfile
  context: .
  buildArgs:
    USE_CUDA: "true"

spec:
  operator: tf
  image: og-marl
  command: wandb agent off-the-grid-marl-team/og-marl-baselines/xxjig0pd

  types:
    Worker:
      count: 1 
 
      resources:
        # 10-15 cpus for single process
        cpus: 4
        # mandatory (must be >= 2): RAM ratio wanted (in GB)
        # memory = cpus * ramRatio
        ramRatio: 2 
        accelerators:
          gpu:
            count: 1
            # mandatory (if gpus amount is > 0): gpu type wanted
            type: gpu 
            product: Quadro-RTX-4000  # Quadro-RTX-4000 | Tesla-V100-SXM3-32GB
