system_name: continuous bc
seed: 42
wandb_project: og-marl
training_steps: 5e5

task:
  source: omiga
  env: mamujoco
  scenario: 6halfcheetah
  dataset: Expert

replay:
  sequence_length: 20
  sample_period: 1

system:
  learning_rate: 3e-4
  linear_layer_dim: 64
  recurrent_layer_dim: 64
  discount: 0.99
  add_agent_id_to_obs: True
