system_name: iddpg+bc
seed: 42
wandb_project: og-marl
training_steps: 5e5

task:
  source: omiga
  env: mamujoco
  scenario: 6halfcheetah
  dataset: Expert
  
replay:
  sequence_length: 10
  sample_period: 1

system:
  linear_layer_dim: 64
  recurrent_layer_dim: 64
  discount: 0.99
  target_update_rate: 0.005
  critic_learning_rate: 3e-4
  policy_learning_rate: 3e-4
  add_agent_id_to_obs: True
  bc_alpha: 2.5
