system_name: qmix
seed: 42
wandb_project: og-marl
environment_steps: 3e6

task:
  source: og_marl
  env: smac_v2
  scenario: terran_10_vs_10 

replay:
  sequence_length: 20
  sample_period: 1
  max_size: 50000

system:
  learning_rate: 3e-4
  linear_layer_dim: 128
  recurrent_layer_dim: 128
  discount: 0.99
  target_update_period: 200
  add_agent_id_to_obs: True
