system_name: discrete+haddpg+cql
seed: 42
wandb_project: og-marl
training_steps: 5e5

task:
  source: og_marl
  env: smac_v1
  scenario: 5m_vs_6m
  dataset: Good

replay:
  sequence_length: 10
  sample_period: 1

system:
  linear_layer_dim: 64
  recurrent_layer_dim: 64
  discount: 0.99
  target_update_rate: 0.01
  critic_learning_rate: 1e-3
  policy_learning_rate: 1e-3
  add_agent_id_to_obs: True
  num_ood_actions: 10
  cql_weight: 5.0
