system_name: "iddpg+bc (torch)"
seed: 42
wandb_project: og-marl
training_steps: 1e5

task:
  source: omar
  env: mamujoco
  scenario: 2halfcheetah
  dataset: Medium

replay:
  sequence_length: 20
  sample_period: 1

system:
  linear_layer_dim: 64
  recurrent_layer_dim: 64
  discount: 0.99
  target_update_rate: 0.005
  critic_learning_rate: 3e-4
  policy_learning_rate: 3e-4
  add_agent_id_to_obs: True
  bc_alpha: 2.5
  device: cuda 